# Generated by Django 3.2 on 2024-01-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.DateField()),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idstudent', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('class_field', models.CharField(db_column='class', max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=45)),
                ('father_name', models.CharField(max_length=45)),
                ('father_telephone', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('mother_telephone', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idsubject', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('idteacher', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('edate', models.DateTimeField()),
                ('cdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_no', models.AutoField(primary_key=True, serialize=False)),
                ('pic_path', models.CharField(max_length=100)),
                ('ocr_path', models.CharField(max_length=100)),
                ('check_result_path', models.CharField(max_length=100)),
                ('exam_id', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
    ]
