# Generated by Django 3.2 on 2024-02-27 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=20)),
                ('edate', models.DateTimeField()),
                ('cdate', models.DateTimeField(auto_now=True)),
                ('llm_knowledge_path', models.CharField(max_length=100, null=True)),
                ('paper_identity_path', models.CharField(max_length=20)),
                ('paper_answer_path', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)])),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exams.teams')),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)])),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exams.teams')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_path', models.CharField(max_length=100)),
                ('ocr_path', models.CharField(max_length=100, null=True)),
                ('llm_result_path', models.CharField(max_length=100, null=True)),
                ('mark_result_path', models.CharField(max_length=100, null=True)),
                ('cdate', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0)),
                ('pages', models.IntegerField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.students')),
            ],
            options={
                'db_table': 'Papers',
            },
        ),
        migrations.AddField(
            model_name='exams',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.teachers'),
        ),
    ]
