# Generated by Django 4.2.10 on 2024-03-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="papers",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
