# Generated by Django 4.2.10 on 2024-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exams_fake_exam_students_fake_student_students_sno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="sno",
            field=models.IntegerField(null=True),
        ),
    ]
