# Generated by Django 3.2 on 2024-01-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('edate', models.DateTimeField()),
                ('cdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_no', models.AutoField(primary_key=True, serialize=False)),
                ('pic_path', models.CharField(max_length=100)),
                ('ocr_path', models.CharField(max_length=100)),
                ('check_result_path', models.CharField(max_length=100)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
    ]
