# Generated by Django 3.2 on 2024-01-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='exam_id',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
